function mask=SegmentFSAseg(aseg)

% This function takes in the FreeSurfer-segmented T1-based volume and
% groups regions into GM, WM, and CSF.


%% Clump regions into CSF, GM, WM
% GM={'Left-Cerebellum-Cortex','Left-Thalamus-Proper','Left-Caudate',...
%     'Left-Putamen','Left-Pallidum','Brain-Stem','Left-Hippocampus',...
%     'Left-Amygdala','Left-Accumbens-area','Left-VentralDC',...
%     'Left-choroid-plexus','Right-Cerebellum-Cortex',...
%     'Right-Thalamus-Proper','Right-Caudate','Right-Putamen',...
%     'Right-Pallidum','Right-Hippocampus','Right-Amygdala',...
%     'Right-Accumbens-area','Right-VentralDC','Right-choroid-plexus'};
GMidx=[3,8,10,11,12,13,16,17,18,26,28,31,42,47,49,50,51,52,53,54,58,60,63];
% WM={'Left-Cerebellum-White-Matter','Right-Cerebellum-White-Matter',...
%     'WM-hypointensities','Left-WM-hypointensities',...
%     'Right-WM-hypointensities','non-WM-hypointensities',...
%     'Left-non-WM-hypointensities','Right-non-WM-hypointensities',...
%     'Optic-Chiasm','CC_Posterior','CC_Mid_Posterior','CC_Central',...
%     'CC_Mid_Anterior','CC_Anterior'};
WMidx=[2,7,41,46,77,78,79,80,81,82,85,251,252,253,254,255];
% CSF={'Left-Lateral-Ventricle','Left-Inf-Lat-Vent','3rd-Ventricle',...
%     '4th-Ventricle','CSF','Left-vessel','Right-Lateral-Ventricle',...
%     'Right-Inf-Lat-Vent','Right-vessel','5th-Ventricle'};
CSFidx=[4,5,14,15,24,30,43,44,62,72];

%% Generate masks
mask.GM=zeros(size(aseg));
mask.WM=zeros(size(aseg));
mask.CSF=zeros(size(aseg));

r=unique(aseg(:));
r(1)=[];
for j=1:length(r)
    if ismember(r(j),GMidx), mask.GM(aseg==r(j))=1;end
    if ismember(r(j),WMidx), mask.WM(aseg==r(j))=1;end
    if ismember(r(j),CSFidx), mask.CSF(aseg==r(j))=1;end
end