%% regcorr
% Performs regression correction by wavelengths.
%
%% Description
% |[data_out, R] = regcorr(data_in, info, hem)| takes a light-level array
% |data_in| of the format MEAS x TIME, and using the scan metadata in
% |info.pairs| and a WL x MEAS |hem| array generated by |gethem|, performs
% a regression correction for each wavelength of the data, which is
% returned in the MEAS x TIME array |data_out|. The corresponding
% correlation coefficients for each measurement are returned in |R| as a
% MEAS x 1 array.
%
%   If y_{r} is the signal to be regressed out and y_{in} is a data
%   time trace (either source-detector or imaged), then the output
%   is the least-squares regression: 
%   y_{out} = y_{in} - y_{r}(<y_{in},y_{r}>/|y_{r}|^2). 
%   Additionally, the correlation coefficient is given by: 
%   R=(<y_{in},y_{r}>/(|y_{in}|*|y_{r}|)).
%
%
%% See Also
% <gethem_help.html gethem> | <detrend_tts_help.html detrend_tts>