function [data_out, R] = regcorr(data_in, info, hem)

% REGCORR Performs regression correction by wavelengths.
%
%   [data_out, R] = REGCORR(data_in, info, hem) takes a light-level data
%   array "data_in" of the format MEAS x TIME, and using the scan metadata
%   in "info.pairs" and a WL x MEAS "hem" array generated by GETHEM,
%   performs a regression correction for each wavelength of the data, which
%   is returned in the MEAS x TIME array "data_out". The corresponding
%   correlation coefficients for each measurement are returned in "R" as a
%   MEAS x 1 array.
%
%   If y_{r} is the signal to be regressed out and y_{in} is a data
%   time trace (either source-detector or imaged), then the output
%   is the least-squares regression: 
%   y_{out} = y_{in} - y_{in}(<y_{in},y_{r}>/|y_{r}|^2). 
%   Additionally, the correlation coefficient is given by: 
%   R=(<y_{in},y_{r}>/(|y_{in}|*|y_{r}|)).
%
% See Also: GETHEM, DETREND_TTS.
% 
% Copyright (c) 2017 Washington University 
% Created By: Adam T. Eggebrecht
% Eggebrecht et al., 2014, Nature Photonics; Zeff et al., 2007, PNAS.
%
% Washington University hereby grants to you a non-transferable, 
% non-exclusive, royalty-free, non-commercial, research license to use 
% and copy the computer code that is provided here (the Software).  
% You agree to include this license and the above copyright notice in 
% all copies of the Software.  The Software may not be distributed, 
% shared, or transferred to any third party.  This license does not 
% grant any rights or licenses to any other patents, copyrights, or 
% other forms of intellectual property owned or controlled by Washington 
% University.
% 
% YOU AGREE THAT THE SOFTWARE PROVIDED HEREUNDER IS EXPERIMENTAL AND IS 
% PROVIDED AS IS, WITHOUT ANY WARRANTY OF ANY KIND, EXPRESSED OR 
% IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY 
% OR FITNESS FOR ANY PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF ANY 
% THIRD-PARTY PATENT, COPYRIGHT, OR ANY OTHER THIRD-PARTY RIGHT.  
% IN NO EVENT SHALL THE CREATORS OF THE SOFTWARE OR WASHINGTON 
% UNIVERSITY BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR 
% CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH 
% THE SOFTWARE, THE USE OF THE SOFTWARE, OR THIS AGREEMENT, WHETHER 
% IN BREACH OF CONTRACT, TORT OR OTHERWISE, EVEN IF SUCH PARTY IS 
% ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

%% Parameters and Initialization.
[Nm, Nt] = size(data_in);
cs = unique(info.pairs.WL); % WLs.
Nc = length(cs); % Number of WLs.
data_out = zeros(Nm, Nt);
R = zeros(Nm, 1);

%% Regression correction.
for k = 1:Nc
    keep = info.pairs.WL == cs(k); % get current color
    temp = data_in(keep, :)';
    
    g = hem(k, :)'; % regressor/noise signal in correct orientation
    gp = pinv(g);
    beta = gp * temp;
    data_out(keep, :) = (temp - g * beta)'; % linear regression
    if exist('vecnorm')
        R(keep) = normrND(g') * normcND(temp); % correlation coefficient
    elseif exist('normr')
        R(keep) = normr(g') * normc(temp); % correlation coefficient
    else
        R(keep) = normRow(g') * normCol(temp); % correlation coefficient
    end
end



%
